TURRET_CONFIG = {
    'baudrate': 9600,
    'serialPort': '/dev/ttyUSB0',
    'noTurret': True,
    'useSSL': False,
    'validationBypass': True,
    'password': "Z",
    'webSocketPort': 9001,
    'certFile': '/etc/uv4l/fullchain.pem',
    'keyFile': '/etc/uv4l/privkey.key'
}
TURRET_COMMANDS = {
    "CMD_FIRE": 0x21,
    "CMD_STOP_FIRE": 0x22,
    "CMD_SAFETY_ON": 0x23,
    "CMD_SAFETY_OFF": 0x24,
    "CMD_REBOOT": 0x25,
    "CMD_ROTATE_LEFT_MAX": 0x26,
    "CMD_ROTATE_ZERO": 0x30,
    "CMD_ROTATE_RIGHT_MAX": 0x3A,
    "CMD_PITCH_DOWN_MAX": 0x3B,
    "CMD_PITCH_ZERO": 0x45,
    "CMD_PITCH_UP_MAX": 0x4F,
}
# array of commands, each command is {msg,cmd,delay}
# 
TEST_COMMANDS = [
    {"msg": "\nInitiating turret commands test...\n",
     "sleep": 3},
    {"msg": "Commanding SAFETY OFF",
     "cmd": TURRET_COMMANDS["CMD_SAFETY_OFF"],
     "sleep": 3},
    {"msg": "Commanding SAFETY ON",
     "cmd": TURRET_COMMANDS["CMD_SAFETY_ON"],
     "sleep": 3},
    {"msg": "Commanding SAFETY OFF",
     "cmd": TURRET_COMMANDS["CMD_SAFETY_OFF"],
     "sleep": 3},
    {"msg": "Firing for 1 second",
     "cmd": TURRET_COMMANDS["CMD_FIRE"],
     "sleep": 1},
    {"cmd": TURRET_COMMANDS["CMD_STOP_FIRE"],
     "sleep": 3},
    {"msg": "Left at speed 7",
     "cmd": TURRET_COMMANDS["CMD_ROTATE_ZERO"] - 7,
     "sleep": 7},
    {"msg": "Right at speed 3",
     "cmd": TURRET_COMMANDS["CMD_ROTATE_ZERO"] + 3,
     "sleep": 7},
    {"msg": "Up at speed 10",
     "cmd": TURRET_COMMANDS["CMD_PITCH_UP_MAX"],
     "sleep": 7},
    {"msg": "Down at speed 1",
     "cmd": TURRET_COMMANDS["CMD_PITCH_ZERO"] - 1,
     "sleep": 7},
    {"msg": "Testing moving and firing",
     "cmd": TURRET_COMMANDS["CMD_ROTATE_ZERO"] + 3},
    {"cmd": TURRET_COMMANDS["CMD_FIRE"],
     "sleep": 1},
    {"cmd": TURRET_COMMANDS["CMD_STOP_FIRE"],
     "sleep": 7},
    {"msg": "Turning safety back on",
     "cmd": TURRET_COMMANDS["CMD_SAFETY_ON"],
     "sleep": 2},
    {"msg": "Test complete. Exiting program."}
]
